config/routes.rb
SampleApp::Application.routes.draw do
	get "users/new"

	root to: 'static_pages#home'

	match '/about',		to: 'static_pages#about'
	match '/contact',	to: 'static_pages#contact'  
    match '/resume',    to: 'static_pages#resume'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def resume
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		by Kevin Cashman
	</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "Kevin J Cashman", '#', id: "logo" %>
    <nav>
    <ul class="nav pull-left">
      <li><%= link_to "Home",    root_path %></li>
      <li><%= link_to "Resume", resume_path %></li>
      <li><%= link_to "Contact",	contact_path %> </li>
    </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Kevin J Cashman</h1>

	<h2> Software Engineer </h2>
</div>